### ISSUE TITLE
[Quay]: Add support for sorting quay repository list view

### ISSUE THREAD

**Issue by karthikjeeyar** [janus-idp/backstage-plugins#1034]
**Describe the bug**
The `SECURITY_SCAN` and `SIZE` columns are not sortable. 

**Expected Behavior**
As a user, I should be able to sort the table by `SECURITY_SCAN` and `SIZE` columns.

**Versions of software used and environment**
Quay plugin v1.4.17

**Screenshot**

![sorting_security_scan](https://github.com/janus-idp/backstage-plugins/assets/9964343/df9a9432-ccc0-4c1d-a708-245244753b9e)

**Comment by Zaperex** [comment]
Resolved by https://github.com/janus-idp/backstage-plugins/pull/1033

**Comment by Zaperex** [comment]
I personally don't believe it makes much sense to be able to sort by security scan since sometimes the scan is not supported. Quay.io also doesn't allow sorting by security scan.

If we do want to implement it, how would we do the tiering? Tags with highest number of higher severity vulnerabilities first? (ex: 2 critical 5 high would be higher than 1 critical and 15 high)
