### ISSUE TITLE
Set up Tekton plugin repo in Janus

### ISSUE THREAD

**Issue by rtaniwa** [janus-idp/backstage-plugins#128]
As a result of the [Tekton spike review,](https://docs.google.com/document/d/1rVDWGcy1dBsNvT6ur_1c_5p52pfZZtVT-6GE0b99F6E/edit?usp=sharing) next step is to:

Populate a new backstage-plugin-tekton repo by using the existing upstream Tekton plugin. Plugin will go into:
https://github.com/janus-idp/backstage-plugins/tree/main/plugins

The configuration should remain as is. Further UI enhancements will be done in a follow-up issue.

**Comment by tumido** [comment]
Can you please elaborate on this plan? If I understand the evaluation doc right, we want to fork the upstream. Why so? 

Upstream tekton plugin consists of 3 different npm packages. So far all the enhancements we're talking about is affecting the frontend side of the plugin only. Is that correct?

What if we just create new frontend plugin instead? A drop in replacement. We can start with a fork, sure. However I don't see a need to have and maintain a separate fork of the **backend** tekton plugin part if we don't expect to make any changes to it for now.

can you please help me understand this @serenamarie125 @rtaniwa ?

**Comment by serenamarie125** [comment]
Tagging @gorkem here as this was his suggestion. He'll be able to better articulate his own reasoning 😄

**Comment by serenamarie125** [comment]
But yes, the vision is to enhance the frontend #111

**Comment by tumido** [comment]
Hey @lokeshrangineni started popping up PRs about this. At this point we have:

- A fork of upstream: https://github.com/janus-idp/backstage-plugin-tekton
- PRs https://github.com/janus-idp/backstage-plugins/pull/135, https://github.com/janus-idp/backstage-plugins/pull/134, https://github.com/janus-idp/backstage-plugins/pull/133 which seems to bring more code as a copy-paste than necessary.

My proposal:
- Bring in the frontend package only as a filtered repository of the upstream fork. That way we are true to preserving authorship of the upstream code in VCS while still allowing us to build upwards on the frontend side.
- Remove the forked repository since we don't need it.

**Comment by tumido** [comment]
@gorkem  Well.. what I want to avoid mostly is duplication of release processes and avoid potential incompatibilities between our plugins, conflicts, supported backstage versions etc. Consistency of CI/CD process in our plugins is also valuable. I want to keep the maintenance const minimal and scalable in future - if we ever decide to fork additional plugins and such.

If we ever intend to use any of those forked plugins (meaning outside of the repository itself), we have to rename and release them anyways. Users still have to install the plugin from NPM.

So I really see 2 options in here:
- Either we fork the upstream and maintain 2 separate CI/CD pipelines and release workflows in 2 different repositories. (Rince and repeat for every forked plugin we want to modify)
- Or we bring in the source code of those plugins into this repository and work on it here. Reusing CI/CD, keeping the same coding standards etc.

If you take a look at the https://github.com/janus-idp/backstage-plugins/pull/137 PR, it works as a drop in replacement for the tekton plugin frontend, crediting the original plugin authors and releasing it under our name and using the same release process as the other janus IDP plugins do.

If we ever need to extend beyond the frontend we can do the same onbaording process for the backend/common packages easily.

**Comment by serenamarie125** [comment]
I thought the recommended approach was this.  Can we confirm this so that we can move further?

> Or we bring in the source code of those plugins into this repository and work on it here. Reusing CI/CD, keeping the same coding standards etc.

**Comment by gorkem** [comment]
I do not think #137 is helping with my concern. The whole idea with the fork was we could quickly modify backend plugin otherwise it is very likely that we will reuse very little from the existing frontend. Perhaps we should delay this work until the actual work of implementing the frontend is started. If the developer(s) assigned to the work asses that there is value to starting from existing frontend they can take #137 into use. However, we still need to figure out how to modify the backend in case we need to but we cross that bridge when we get there.

**Comment by lokeshrangineni** [comment]
@tumido - This is new information for me. Do we have already a working backend (not the one from [jquad-tekton-backend code](https://github.com/jquad-group/backstage-jquad/tree/main/plugins/tekton-pipelines-backend)) code? Whatever decision you both make please let me know. I m happy to make changes to the original PR which I created [135](https://github.com/janus-idp/backstage-plugins/pull/135).

**Comment by rtaniwa** [comment]
Doing some housekeeping, seems like we will no longer require this issue due to investigation done in issue 161 so I am going to close this one out. @invincibleJai will close out the related PR.
