### ISSUE TITLE
OCM: Make imported clusters consumable by kubernetes plugin

### ISSUE THREAD

**Issue by tumido** [janus-idp/backstage-plugins#139]
**Is your feature request related to a problem? Please describe.**
As of now, OCM plugin is capable of discovering managed clusters. It stores them in catalog as `Resource` with type: `kubernetes-cluster`. This makes them eligible to be consumed by kubernetes plugin allowing workload display.  

**Describe the solution you'd like**
Make it so that user can configure their backstage with:

```yaml
kubernetes:
  ...
  clusterLocatorMethods:
    ...
    - type: 'catalog'
```

And clusters are properly mapped and authenticated.

This requires populating [necessary annotations](https://github.com/backstage/backstage/blob/084472316c480ebeefc30d0d99f3efabedca468b/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L58-L84) and providing a proper auth method via OIDC.

If all clusters are configured to accept the same identity provider via [OAuth](https://docs.openshift.com/container-platform/4.10/authentication/understanding-identity-provider.html) we should be able to use the same provider here.

We should also be able to verify this using `oauth2Proxy`. I think we can't use the underlying openshift (the cluster which Backstage is deployed to) as the proxy target. But if we use keycloak instead (assuming the same keycloak is used as OAuth provider for all managed clusters) it should work.

**Describe alternatives you've considered**

Alternatively we may require to authenticate via [Managed SA (OCM addon)](https://github.com/open-cluster-management-io/managed-serviceaccount) ([proposal](https://github.com/open-cluster-management-io/enhancements/tree/main/enhancements/sig-architecture/19-projected-serviceaccount-token)). It may be problematic to ensure proper token propagation. This solution also doesn't provide any RBAC.

**Additional context**

Relevant links

- [Kubernetes plugin config for catalog](https://backstage.io/docs/features/kubernetes/configuration#catalog)
- [Catalog cluster locator](https://github.com/backstage/backstage/blob/master/plugins/kubernetes-backend/src/cluster-locator/CatalogClusterLocator.ts#L43)
- https://backstage.io/docs/auth/oauth2-proxy/provider
- https://docs.openshift.com/container-platform/4.10/authentication/understanding-identity-provider.html

**Comment by tumido** [comment]
Replaces https://github.com/operate-first/service-catalog/issues/177

**Comment by SamoKopecky** [comment]
We tried to create POC of the first solution mentioned in the issue and discovered that if we want to implement user authorization using the cluster entities together with third party generated `oidc` tokens we would need to:
- Expand the list of available `oidcTokenProvider`s, since right now the only supported providers are `google`, `azure`, `okta` and `onelogin` (see [docs](https://backstage.io/docs/features/kubernetes/configuration#clustersoidctokenprovider-optional)). This would require changes to the upstream Kubernetes plugin.
- When we expand the list of available providers, theres now the issue with the fact that OCP doesn't support authorization using 3rd party `oidc` tokens, which is how the `oidc` auth provider works in Backstage (see [docs](https://backstage.io/docs/features/kubernetes/configuration#clustersoidctokenprovider-optional)). This requires changes in the OCP auth system.
