### ISSUE TITLE
[Topology] Topology page throws an error when workload is clicked

### ISSUE THREAD

**Issue by debsmita1** [janus-idp/backstage-plugins#267]
**Describe the bug**
The Topology page in the dev mode throws an error when a workload is clicked.

**To Reproduce**
- Setup the Topology plugin
- Run command:
```
yarn workspace @janus-idp/backstage-plugin-topology run start
```
**GIF/Screenshot**
Error:
<img width="1646" alt="Screenshot 2023-04-19 at 5 18 01 PM" src="https://user-images.githubusercontent.com/22490998/233065665-62833330-8eb0-4e35-a75d-a6da97999e71.png">

dev mode:
https://user-images.githubusercontent.com/22490998/232798401-8904122b-7d68-4016-81c5-516487457653.mov

app:
https://user-images.githubusercontent.com/22490998/233063800-4b6cd64b-5325-41f5-8124-c21f7db919fb.mov

**Expectation:**
It should open the side panel when a workload is clicked

**Comment by invincibleJai** [comment]
Thanks @divyanshiGupta for looking into it.

@fmenesesg Pls check if the above helps in your environment as well

**Comment by fmenesesg** [comment]
I try it, but I'm still facing the same issue

**Comment by invincibleJai** [comment]
this is a tricky one, as this issue is observed with multiple versions of d3 and it's dependencies on backstage instances so not a standalone issue with pf react-topology either. Have opened an issue in pf https://github.com/patternfly/react-topology/issues/44.

this PR https://github.com/janus-idp/backstage-plugins/pull/280 helps with fixing this for the time being as work around
