### ISSUE TITLE
🔌 Plugin: ins

### ISSUE THREAD

**Issue by ghost** [janus-idp/backstage-plugins#699]
### 🔖 Summary

install RHEL OS

### 👀 Have you spent some time to check if this plugin request has been raised before?

- [X] I checked and didn't find similar issue

### 🏢 Have you read the Code of Conduct?

- [X] I have read the [Contributing Guidelines](https://github.com/backstage/backstage/blob/master/CODE_OF_CONDUCT.md)

### Are you willing to submit PR?

None

**Comment by tumido** [comment]
Seems like the requestor is gone - deleted user.

This plugin request doesn't provide enough detail for us to act upon it. "Install RHEL" can mean a lot of things... And since the original issue author deleted their account, we can't ask for details.

In case anybody else would like to see such plugin happen and would like to provide us with more backstory feel free to comment or open a new issue. For the time being, I'm closing this one.
