### ISSUE TITLE
App Topology - Evaluate connecting Topology (backstage plugin) with cluster

### ISSUE THREAD

**Issue by invincibleJai** [janus-idp/backstage-plugins#91]
**Description**
As a developer, I want to visualize resources of Deployment kind and Deployment Config Kind with pods ring demonstrating pod status and decorators for the route in a sample plugin for topology as Read-only. This will require connecting with the cluster and evaluating if we can list/watch k8s resources from the cluster, if not what is that needed to get to it?

**Acceptance Criteria**
- [x] evaluating if we can list/watch k8s resources from the cluster
- [x] Do we need to use [k8s plugin](https://github.com/backstage/backstage/tree/master/plugins/kubernetes)?
- [x] Do we need Topology-backend for this?

**Comment by divyanshiGupta** [comment]
K8s plugin can be used to get the entity's resources from a cluster for the topology plugin. Currently there is only support for listing the resources and instead of watching the resources for updates, polling is done at a set interval.

Currently there is no need of a separate backend as we can use the k8s plugin api to consume the cluster resources.

Steps to use k8s plugin api to get the service objects in a separate plugin:

- Install and configure kubernetes plugin by following these guides:
  - https://backstage.io/docs/features/kubernetes/installation
  - https://backstage.io/docs/features/kubernetes/configuration
- In the plugin component you want to fetch the resources in, first get the entity (const { entity } = useEntity()) whose resource you want to list.
- Now using `useKubernetesObjects` hook (const { kubernetesObjects, error } = useKubernetesObjects(entity)) get the k8s resources.

Note:
K8s plugin identifies if the provided entity has k8s resources and if yes from which namespace it should get the resources based on the following annotations added to the entity's catalog-info.yaml
`annotations:
 'backstage.io/kubernetes-id': dice-roller
 'backstage.io/kubernetes-namespace': dice-space
`
For k8s plugin to get the desired entity's k8s resources the following label should be added to the resources
`'backstage.io/kubernetes-id': <BACKSTAGE_ENTITY_NAME>`

A custom label selector can also be added which will then be used by Backstage to find the resources. The label selector takes precedence over the id annotation.
`backstage.io/kubernetes-label-selector': 'app=my-app,component=front-end`

In order to use k8s plugin to get the resources for Topology view, the above annotations/labels should be in place.

cc: @serenamarie125 @christophe-f
